
if settings.startup['composite-combinators-dev-mode'].value then

data:extend({
  {
    type = "selection-tool",
    name = "composite-combinator-str",
    icon = "__CompositeCombinatorsCore__/graphics/tools/string_tool.png",
    icon_size = 32,
    stack_size = 1,
    subgroup = "tool",
    order = "c[automated-construction]-d[composite-combinator-str]",
    flags = {"hidden"},
    selection_color = {r = 0.2, g = 0.8, b = 0.2, a = 0.2},
    alt_selection_color = {r = 0.2, g = 0.2, b = 0.8, a = 0.2},
    selection_mode = {"buildable-type"},
    alt_selection_mode = {"buildable-type"},
    selection_cursor_box_type = "entity",
    alt_selection_cursor_box_type = "copy",
    can_be_mod_opened = true,
    show_in_library = false,
  }, 
  {
    type = "shortcut",
    name = "composite-combinator-str",
    item_to_create = "composite-combinator-str",
    order = "a[alt-mode]-b[copy]",
    action = "create-blueprint-item",
    -- localised_name = {"shortcut.upgrade-builder"},
    icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/string_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    small_icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/string_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    disabled_small_icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/string_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    -- style = "green",
  },
  --[[{
    type = "selection-tool",
    name = "composite-combinator-test-reserialize",
    icon = "__CompositeCombinatorsCore__/graphics/tools/verify_tool.png",
    icon_size = 32,
    stack_size = 1,
    subgroup = "tool",
    order = "c[automated-construction]-d[composite-combinator-test-reserialize]",
    flags = {"hidden"},
    selection_color = {r = 0.2, g = 0.8, b = 0.2, a = 0.2},
    alt_selection_color = {r = 0.2, g = 0.2, b = 0.8, a = 0.2},
    selection_mode = {"buildable-type"},
    alt_selection_mode = {"buildable-type"},
    selection_cursor_box_type = "entity",
    alt_selection_cursor_box_type = "copy",
    can_be_mod_opened = true,
    show_in_library = false,
  }, 
  {
    type = "shortcut",
    name = "composite-combinator-test-reserialize",
    item_to_create = "composite-combinator-test-reserialize",
    order = "a[alt-mode]-b[copy]",
    action = "create-blueprint-item",
    -- localised_name = {"shortcut.upgrade-builder"},
    icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/verify_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    small_icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/verify_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    disabled_small_icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/verify_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    -- style = "green",
  },]]--
  {
    type = "selection-tool",
    name = "composite-combinator-component-str",
    icon = "__CompositeCombinatorsCore__/graphics/tools/component_string_tool.png",
    icon_size = 32,
    stack_size = 1,
    subgroup = "tool",
    order = "c[automated-construction]-d[composite-combinator-component-str]",
    flags = {"hidden"},
    selection_color = {r = 0.2, g = 0.8, b = 0.2, a = 0.2},
    alt_selection_color = {r = 0.2, g = 0.2, b = 0.8, a = 0.2},
    selection_mode = {"buildable-type"},
    alt_selection_mode = {"buildable-type"},
    selection_cursor_box_type = "entity",
    alt_selection_cursor_box_type = "copy",
    can_be_mod_opened = true,
    show_in_library = false,
  }, 
  {
    type = "shortcut",
    name = "composite-combinator-component-str",
    item_to_create = "composite-combinator-component-str",
    order = "a[alt-mode]-b[copy]",
    action = "create-blueprint-item",
    -- localised_name = {"shortcut.upgrade-builder"},
    icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/component_string_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    small_icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/component_string_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    disabled_small_icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/component_string_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    -- style = "green",
  },
  --[[{
    type = "selection-tool",
    name = "composite-combinator-composite-str",
    icon = "__CompositeCombinatorsCore__/graphics/tools/composite_string_tool.png",
    icon_size = 32,
    stack_size = 1,
    subgroup = "tool",
    order = "c[automated-construction]-d[composite-combinator-composite-str]",
    flags = {"hidden"},
    selection_color = {r = 0.2, g = 0.8, b = 0.2, a = 0.2},
    alt_selection_color = {r = 0.2, g = 0.2, b = 0.8, a = 0.2},
    selection_mode = {"buildable-type"},
    alt_selection_mode = {"buildable-type"},
    selection_cursor_box_type = "entity",
    alt_selection_cursor_box_type = "copy",
    can_be_mod_opened = true,
    show_in_library = false,
  }, 
  {
    type = "shortcut",
    name = "composite-combinator-composite-str",
    item_to_create = "composite-combinator-composite-str",
    order = "a[alt-mode]-b[copy]",
    action = "create-blueprint-item",
    -- localised_name = {"shortcut.upgrade-builder"},
    icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/composite_string_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    small_icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/composite_string_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    disabled_small_icon = {
      filename = "__CompositeCombinatorsCore__/graphics/tools/composite_string_tool.png",
      priority = "extra-high-no-scale",
      size = 32,
      scale = 1,
      flags = {"icon"},
    },
    -- style = "green",
  },]]--
})

end