inspect = require('code.inspect')

require('code.util')
require('code.misc')
require('code.components')
require('code.entry')
require('code.funcmain')
require('code.func')
require('code.game')
require('code.tests')